CREATE DATABASE RRHH
USE RRHH
--DROP DATABASE RRHH
-- CREANDO LA TB OFICINA
GO
CREATE TABLE OFICINA (
    idOficina CHAR(2) PRIMARY KEY,
    nomOficina VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB OFICINA
GO
CREATE TABLE CARGO (
    idCargo CHAR(2) PRIMARY KEY,
    nomCargo VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB REGIMEN_LABORAL
GO
CREATE TABLE REGIMEN_LABORAL (
    idRegimen CHAR(1) PRIMARY KEY,
    nomRegimen VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB EMPLEADO
GO
CREATE TABLE EMPLEADO (
    idEmpleado CHAR(4) PRIMARY KEY CHECK(idEmpleado LIKE 'E[0-9][0-9][0-9]'),
    nomApe VARCHAR(40) NOT NULL,
    fechaIngreso DATE NOT NULL,
    idOficina CHAR(2) REFERENCES Oficina(idOficina),
    idRegimen CHAR(1) REFERENCES Regimen_Laboral(idRegimen),
    sueldo INT NOT NULL,
    idCargo CHAR(2) REFERENCES Cargo(idCargo)
)
GO

-- CREANDO LA TB ESTADO
GO
CREATE TABLE ESTADO (
    idEstado CHAR(1) PRIMARY KEY,
    nomEstado VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB TIPO_LICENCIA
GO
CREATE TABLE TIPO_LICENCIA (
    idTipo_Licencia CHAR(1) PRIMARY KEY,
    nomTipo_Licencia VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB MODALIDAD_LICENCIA
GO
CREATE TABLE MODALIDAD_LICENCIA (
    idModalidad CHAR(1) PRIMARY KEY,
    nomModalidad VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB LICENCIAS
GO
CREATE TABLE LICENCIAS (
    idLicencia CHAR(5) PRIMARY KEY,
    idEmpleado CHAR(4) REFERENCES EMPLEADO(idEmpleado),
    fechaSolicitud DATE NOT NULL,
    idTipo_Licencia CHAR(1) REFERENCES TIPO_LICENCIA(idTipo_Licencia),
    fechaInicio DATE NOT NULL,
    fechaFin DATE NOT NULL,
    idModalidad CHAR(1) REFERENCES MODALIDAD_LICENCIA(idModalidad),
    idEstado CHAR(1) REFERENCES ESTADO(idEstado)
)
GO

-- CREANDO LA TB CONTROL_ASISTENCIA
GO
CREATE TABLE CONTROL_ASISTENCIA (
    idControl CHAR(5) PRIMARY KEY,
    idEmpleado CHAR(4) REFERENCES EMPLEADO(idEmpleado),
    fecha DATE NOT NULL,
    horaIngreso TIME NOT NULL,
    horaSalida TIME NOT NULL
)
GO

-- CREANDO LA TB TIPO_CONCEPTO
GO
CREATE TABLE TIPO_CONCEPTO (
    idTipo_Concepto CHAR(1) PRIMARY KEY,
    nomTipo_Concepto VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB SITUACION
GO
CREATE TABLE SITUACION (
    idSituacion CHAR(1) PRIMARY KEY,
    nomSituacion VARCHAR(40) UNIQUE NOT NULL
)
GO

-- CREANDO LA TB CONCEPTO
GO
CREATE TABLE CONCEPTO (
    idConcepto CHAR(2) PRIMARY KEY,
    nomDescripcion VARCHAR(40) UNIQUE NOT NULL,
    monto INT NOT NULL,
    tasa INT NOT NULL,
    idTipo_Concepto CHAR(1) REFERENCES TIPO_CONCEPTO(idTipo_Concepto),
    idSituacion CHAR(1) REFERENCES SITUACION(idSituacion)
)
GO

-- CREANDO LA TB PLANILLA_REMUNERACIONES
GO
CREATE TABLE PLANILLA_REMUNERACIONES (
    idPlanilla CHAR(5) PRIMARY KEY,
    idEmpleado CHAR(4) REFERENCES EMPLEADO(idEmpleado),
    periodo CHAR(7) CHECK(periodo LIKE '20[0-9][0-9]-[0-1][0-9]'),
    faltas INT NOT NULL,
    tardanzas INT NOT NULL,
    sueldo_neto INT NOT NULL
)
GO

-- CREANDO LA TB DETALLE_REMUNERACIONES  NO ENTIENDOOOOO
GO
CREATE TABLE DETALLE_REMUNERACIONES (
    idPlanilla CHAR(5) REFERENCES PLANILLA_REMUNERACIONES(idPlanilla),
    idConcepto CHAR(2) REFERENCES CONCEPTO(idConcepto),
    monto INT NOT NULL,
    PRIMARY KEY (idPlanilla, idConcepto)
)
GO
