-- SELECTS
SELECT * FROM OFICINA ORDER BY idOficina
SELECT * FROM CARGO ORDER BY idCargo
SELECT * FROM REGIMEN_LABORAL ORDER BY idRegimen
SELECT * FROM EMPLEADO ORDER BY idEmpleado
SELECT * FROM ESTADO ORDER BY idEstado
SELECT * FROM TIPO_LICENCIA ORDER BY idTipo_Licencia
SELECT * FROM MODALIDAD_LICENCIA ORDER BY idModalidad
SELECT * FROM LICENCIAS ORDER BY idLicencia
SELECT * FROM CONTROL_ASISTENCIA ORDER BY idControl
SELECT * FROM TIPO_CONCEPTO
SELECT * FROM SITUACION ORDER BY idSituacion
SELECT * FROM CONCEPTO ORDER BY idConcepto
SELECT * FROM PLANILLA_REMUNERACIONES ORDER BY idPlanilla
SELECT * FROM DETALLE_REMUNERACIONES